name: 多看点

on:
  workflow_dispatch:
  schedule:
     - cron: '27 23,0-15 * * *'
  watch:
    types: started
env:
    TZ: Asia/Shanghai

jobs:
    build:
        runs-on: ubuntu-latest
 
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: npm install
              if: env.DKDBODY
              run: |
                 npm install
            - name: '运行 【多看点】'
              if: env.DKDBODY
              run: |
                node dkd_coin.js
              env:
                dkdurl: ${{ secrets.DKDURL }}
                dkdbody: ${{ secrets.DKDBODY }}
                dkdhd: ${{ secrets.DKDHD }}

