name: 羊毛赚

on:
  workflow_dispatch:
  schedule:
     - cron: '15 0 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        ymzhd: ${{ secrets.YMZHD }}
        ymzbody: ${{ secrets.YMZBODY }}
        ymzbody1: ${{ secrets.YMZBODY1 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.YMZHD
        run: |
          npm install
      - name: '运行 【羊毛赚】'
        if: env.YMZHD
        run: |
          node Task/ymz.js
